### ISSUE TITLE
Installation impossible !

### ISSUE THREAD

**Issue by Azrty** [MineWeb/Plugin-NewsAdvanced#1]
Il est impossible pour moi, d’installer le plugin, erreur:
![ea31e6a0-3779-4631-8343-a5f10e248fde](https://user-images.githubusercontent.com/38593367/39219714-4401947c-47fa-11e8-99b8-607ee762978d.jpeg)

**Comment by Eywek** [comment]
En effet
```2018-05-13 15:09:55 Error: Plugin "NewsAdvanced" not valid! The file or folder "/var/www/cms_mineweb_1.3.6/app/Plugin/NewsAdvanced/Model" doesn't exist! Please verify documentation for more informations.```

Git ne push pas les dossiers vide, il faut donc mettre un `.gitkeep` par exemple.

**Comment by Azrty** [comment]
Ah

**Comment by Azrty** [comment]
@NorthenFlo ?

**Comment by ClementGuerin** [comment]
#3
